# Generated by Django 4.2.14 on 2025-02-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneverification',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
