# Generated by Django 4.2.14 on 2025-02-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_phoneverification_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneverification',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
